### ISSUE TITLE
TODO v0.1

### ISSUE THREAD

**Issue by felipefcm** [felipefcm/wordle-react#1]
# Version 0.1

Screen should show the main board and a virtual keyboard.
Standard Wordle game, 5-letter words and up to 6 attempts.
After all attempts are made, or word is discovered, the game just ends and needs refresh to run again.

This was quite a big undertaking. I wanted to make a very simple initial version but just couldn't. Added backend so the client won't know the solution until the end and it sends a request with each attempt made to evaluate. Attempt evaluation wasn't as simple as I initially thought, handling duplicates were kinda tricky. I probably don't have the nicest algorithm, but it works.
Added automated testing for the most important modules, that was fun.

### LetterCell
- [x] Create component
- [x] Create box with border
- [x] Create letter
- [x] Add prop telling which state the cell is (not in word, incorrect position, correct position)
- [x] Set bg colour depending on cell state

### WordAttempt
- [x] Create component to encapsulate multiple `LetterCell`s
- [x] Listen to virtual keyboard clicks and update the cells accordingly

### VirtualKeyboard
- [x] Create VirtualKeyboard component
- [x] Read rows from array
- [x] Add Complete button to submit word
- [x] Add Backspace button
- [x] Change keys bg colours depending on previous attempts

### Game
- [x] After all letters have been typed, define state of `LetterCell`s
- [x] Update current attempt index
- [x] If all letters correct or all attempts were made, game ends
- [x] Add message to inform that game was won or lost
- [x] Fix attempt evaluation when there are duplicate letters

### Backend
- [x] Handle requests with attempt to be evaluated using fixed word
