### ISSUE TITLE
TODO v0.3

### ISSUE THREAD

**Issue by felipefcm** [felipefcm/wordle-react#14]

**Comment by felipefcm** [comment]
This version aims to fix some usability issues in the front-end.

- [ ] Fix virtual keyboard letters having incorrect background position depending on screen width
- [ ] Add loading states when API requests are made
- [ ] Lock input when in a loading state
