### ISSUE TITLE
TODO v0.2

### ISSUE THREAD

**Issue by felipefcm** [felipefcm/wordle-react#2]
This version will improve the backend. It will include a cloud infrastructure project using Serverless Stack (SST), so we can use the AWS CDK to specify and provision resources. There will be a words table storing all the possible words in the game. Later, we'll also store the last date it was used, as to avoid using the same words on days to close to each other.
The backend will need to validate incoming attempts, by querying the database.

### Infra
- [x] Setup SST project
- [x] Setup Actions for deployment and OIDC in AWS
- [x] Create `words` table to store words: make the word itself the PK

### Backend
- [x] Add internal endpoint for populating the words table
- [x] Validate incoming word. It must be in dictionary
