### ISSUE TITLE
TODO v0.3

### ISSUE THREAD

**Issue by felipefcm** [felipefcm/wordle-react#9]
This version will further improve the backend with match generation and user authentication.

- [ ] Create endpoint to generate new match, given user id

### Match
- [ ] Add authentication method to identify user
- [ ] Add button to allow new match to be requested
- [ ] Handle new match creation
